ONE_PLACE = 'одноместный'
SECOND_PLACE = 'двухместный'
SEMILUXE = 'полулюкс'
LUXE = 'люкс'

STANDART = 'стандарт'
STANDART_UP = 'стандарт_улучшенный'
APART = 'апартамент'

HALF_BOARD = 'полупансион'
BREAKFAST = 'завтрак'
WITHOUT_FOOD = 'без питания'

OPTION_ROOM = 'мы можем вам предложить следующий вариант: Номер комнаты'
OPTION_COMFORT = 'Степень комфортности'
OPTION_FOOD = 'Вид питания'
OTHER_OPTION = 'хорошо, поищем другие варианты'
CANT_BOOK = 'не можем вас заселить'

YES = 'Да'
NO = 'Нет'

BOOKED_ROOMS = 'Количество занятых номеров на'
NOT_BOOKED_ROOMS = 'Количество свободных номеров на'
PERC_BOOKED_HOTEL = 'Процент загруженности гостиницы на'
PERC_BOOKED_ONE_PLACE = 'Процент загруженности одноместных номеров на'
PERC_BOOKED_SECOND_PLACE = 'Процент загруженности двухместных номеров на'
PERC_BOOKED_SEMILUXE = 'Процент загруженности полулюкс номеров на'
PERC_BOOKED_LUXE = 'Процент загруженности люкс номеров на'
GET_INCOME = 'Полученный доход за'
MISSED_INCOME = 'Упущенный доход за'
